language: java
jdk:
 - openjdk8
 - openjdk9
 - openjdk10
 - oraclejdk11
 - openjdk12
 - openjdk13
 - openjdk14
addons:
  apt:
    packages:
      - oracle-java11-installer
install :
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DbatchAnswers=n
script:
  - mvn install
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
