language: java
jdk:
 - openjdk8
 - openjdk9
 - openjdk10
 - openjdk11
 - openjdk12
 - openjdk13
 - openjdk14
matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install :
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DbatchAnswers=n
script:
  - mvn install
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
