language: java
jdk:
 - openjdk8
 - openjdk9
 - openjdk10
 - openjdk11
 - openjdk12
 - openjdk13
 - openjdk14
before_install:
  - echo $JAVA_HOME
  - which java
  - sudo rm -rf /usr/local/lib/jvm/
  - sudo apt-get install -y openjdk-11-jdk-headless
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - which java
  - java -version
  - $JAVA_HOME/bin/java -version
install :
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DbatchAnswers=n -Djdk.tls.client.protocols=TLSv1.2
script:
  - mvn install -Djdk.tls.client.protocols=TLSv1.2
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
