language: java
jdk:
 - openjdk8
 - openjdk9
 - openjdk10
 # Commenting out openjdk11 for now because of javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
 # This is a jdk bug which was fixed in openjdk version "11.0.3" but travis runs openjdk version "11.0.2"
 # - openjdk11 
 - openjdk12
 - openjdk13
 - openjdk14
install :
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DbatchAnswers=n
script:
  - mvn install
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
